"""Final T3 vs T1 head-to-head analysis on the 6-way active panel.

Reads the 6-way equity parquets, computes per-window APYs for T1 and
T3, runs paired-bootstrap on the 6 ΔAPY = (T3 − T1) deltas, and
produces a publication-ready summary table + LaTeX macros for paper
section V.

Outputs:
* results/institutional/tables/t3_vs_t1_paired_bootstrap.csv
* papers/icicpe-scopus-vol2/sections/t3_macros.tex

This closes pre-registered H1c.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

EQ_6W = ROOT / "results/institutional/tables/equity_walk_forward_6way"
BPY = 365 * 24 * 60 * 60 // 12
WINDOWS = ["W1", "W2", "W3", "W4", "W5", "W6"]


def _apy_from_eq(path: Path) -> float | None:
    if not path.exists():
        return None
    eq = pd.read_parquet(path)
    initial = float(eq["position_usd"].iloc[0])
    final = float(eq["position_usd"].iloc[-1])
    years = max(len(eq) / BPY, 1e-9)
    return ((final / initial) ** (1.0 / years) - 1.0) * 100


def _bootstrap_paired(deltas: np.ndarray, *, B: int = 10_000,
                      seed: int = 42) -> dict:
    rng = np.random.default_rng(seed)
    n = len(deltas)
    boots = np.array([deltas[rng.integers(0, n, n)].mean() for _ in range(B)])
    return {
        "mean": float(deltas.mean()),
        "std": float(deltas.std(ddof=1)),
        "ci_low_95": float(np.percentile(boots, 2.5)),
        "ci_high_95": float(np.percentile(boots, 97.5)),
        "p_one_sided_le0": float((boots <= 0).mean()),
        "wins": int((deltas > 0).sum()),
        "n_windows": n,
    }


def main() -> int:
    rows = []
    deltas = []
    print(f"{'Window':>6} {'T1 APY':>9} {'T3 APY':>9} {'Δ bp':>7} {'T1 reb':>7} {'T3 reb':>7}")
    print("-" * 56)
    for w_idx, wid in enumerate(WINDOWS, start=1):
        t1f = EQ_6W / f"w{w_idx}_t1_threshold.parquet"
        t3f = EQ_6W / f"w{w_idx}_t3_hazard.parquet"
        if not (t1f.exists() and t3f.exists()):
            print(f"  {wid}    -- MISSING --")
            continue
        a1 = _apy_from_eq(t1f)
        a3 = _apy_from_eq(t3f)
        e1 = pd.read_parquet(t1f)
        e3 = pd.read_parquet(t3f)
        r1 = int(e1.current_protocol.ne(e1.current_protocol.shift()).sum() - 1)
        r3 = int(e3.current_protocol.ne(e3.current_protocol.shift()).sum() - 1)
        d_bp = (a3 - a1) * 100
        deltas.append(d_bp)
        rows.append({
            "window_id": wid,
            "t1_apy_pct": a1,
            "t3_apy_pct": a3,
            "delta_bp": d_bp,
            "t1_rebal": r1,
            "t3_rebal": r3,
        })
        print(f"  {wid}    {a1:8.3f}% {a3:8.3f}% {d_bp:+7.2f} {r1:>7d} {r3:>7d}")

    df = pd.DataFrame(rows)
    out_csv = ROOT / "results/institutional/tables/t3_vs_t1_paired_bootstrap.csv"
    df.to_csv(out_csv, index=False)
    print(f"\nwrote per-window table to {out_csv.name}")

    if len(deltas) < 2:
        print("not enough windows for bootstrap — need at least 2 deltas")
        return 0

    deltas_arr = np.array(deltas)
    stats = _bootstrap_paired(deltas_arr)
    print("\n=== Paired bootstrap T3 − T1 (basis points, ΔAPY) ===")
    print(f"  N windows:            {stats['n_windows']}")
    print(f"  Mean Δ:               {stats['mean']:+.2f} bp")
    print(f"  Std Δ:                {stats['std']:.2f} bp")
    print(f"  95% CI:               [{stats['ci_low_95']:+.2f}, {stats['ci_high_95']:+.2f}] bp")
    print(f"  p-value (one-sided):  {stats['p_one_sided_le0']:.4f}")
    print(f"  Wins (Δ>0):           {stats['wins']}/{stats['n_windows']}")
    print(f"  H1c (ΔAPY > 0):       "
          f"{'✓ CONFIRMED' if stats['p_one_sided_le0'] < 0.05 else 'directional only (p≥0.05)'}")

    stats_path = ROOT / "results/institutional/tables/t3_vs_t1_bootstrap_stats.json"
    stats_path.write_text(json.dumps(stats, indent=2))

    # LaTeX macros for paper §V
    macros = ROOT / "papers/icicpe-scopus-vol2/sections/t3_macros.tex"
    macros_text = f"""% Auto-generated by scripts/analyze_t3_vs_t1.py
% T3 sophisticated Cox model vs T1 gas-aware threshold, 6-way active panel
\\newcommand{{\\TThreeMeanDeltaBp}}{{{stats['mean']:+.2f}}}
\\newcommand{{\\TThreeStdBp}}{{{stats['std']:.2f}}}
\\newcommand{{\\TThreeCILow}}{{{stats['ci_low_95']:+.2f}}}
\\newcommand{{\\TThreeCIHigh}}{{{stats['ci_high_95']:+.2f}}}
\\newcommand{{\\TThreePValue}}{{{stats['p_one_sided_le0']:.4f}}}
\\newcommand{{\\TThreeWins}}{{{stats['wins']}}}
\\newcommand{{\\TThreeNWindows}}{{{stats['n_windows']}}}
"""
    macros.write_text(macros_text, encoding="utf-8")
    print(f"\nwrote LaTeX macros to {macros.name}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
