"""Fill papers/icicpe-scopus-vol2/sections/results_macros.tex from
real per-block-panel matrix CSVs (2026-05-26)."""
from __future__ import annotations

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
MATRIX_CSV = ROOT / "results" / "tables" / "test_matrix.csv"
H1_CSV = ROOT / "results" / "tables" / "h1_significance.csv"
REGIME_CSV = ROOT / "results" / "tables" / "regime_breakdown.csv"
OUT_TEX = ROOT / "papers" / "icicpe-scopus-vol2" / "sections" / "results_macros.tex"


def main() -> int:
    matrix = pd.read_csv(MATRIX_CSV).set_index("policy")
    h1 = pd.read_csv(H1_CSV).set_index("hypothesis")
    regime = pd.read_csv(REGIME_CSV)

    POLICY_PREFIX = {
        "b1_always_aave": "Buyhold",
        "b2_always_compound": "BuyholdCompound",
        "b3_greedy_spot": "Greedy",
        "b4_mcdm_ema": "EMA",
        "t1_threshold": "TOne",
        "t2_optimal_stopping": "TTwo",
        "t3_hazard": "TThree",  # added when --include-t3 row is present
    }

    lines = [
        r"% Vol-2 results macros, autogenerated by scripts/fill_vol2_macros.py.",
        r"% Sources: results/tables/{test_matrix,regime_breakdown,h1_significance}.csv",
        r"% Per-block panel: 3.9M rows (Nov 2024 - Apr 2026), 3 protocols",
        r"% (Aave V3 + Morpho Blue + Euler V2). Test window Jan-Apr 2026.",
        r"",
    ]

    for p, prefix in POLICY_PREFIX.items():
        if p not in matrix.index:
            # Provide --- placeholders so latex never sees undefined macros.
            for suf in ("APY", "NRebal", "GasUSD", "MaxDD", "FinalEquity"):
                lines.append(rf"\newcommand{{\{prefix}{suf}}}{{---}}")
            lines.append(r"")
            continue
        r = matrix.loc[p]
        lines += [
            rf"\newcommand{{\{prefix}APY}}{{{r.net_apy_pct:.2f}\%}}",
            rf"\newcommand{{\{prefix}NRebal}}{{{int(r.n_rebalances)}}}",
            rf"\newcommand{{\{prefix}GasUSD}}{{\${r.gas_spent_usd:,.0f}}}",
            rf"\newcommand{{\{prefix}MaxDD}}{{{r.max_drawdown_pct:+.3f}\%}}",
            rf"\newcommand{{\{prefix}FinalEquity}}{{\${r.final_equity_usd:,.0f}}}",
            r"",
        ]

    H1_PREFIX = {
        "H1a": "HOneA",
        "H1b": "HOneB",
        "H1c": "HOneC",                # T3 vs T2 (present after --include-t3)
        "H1aux_t1_vs_b1": "HOneAux",
    }
    for hyp, prefix in H1_PREFIX.items():
        if hyp not in h1.index:
            for suf in ("Delta", "CIlow", "CIhigh", "Pvalue", "NMonths"):
                lines.append(rf"\newcommand{{\{prefix}{suf}}}{{---}}")
            lines.append(r"")
            continue
        r = h1.loc[hyp]
        lines += [
            rf"\newcommand{{\{prefix}Delta}}{{{r.delta_sharpe_point:+.3f}}}",
            rf"\newcommand{{\{prefix}CIlow}}{{{r.ci_low_95:+.3f}}}",
            rf"\newcommand{{\{prefix}CIhigh}}{{{r.ci_high_95:+.3f}}}",
            rf"\newcommand{{\{prefix}Pvalue}}{{{r.nominal_p:.3f}}}",
            rf"\newcommand{{\{prefix}NMonths}}{{{int(r.n_months)}}}",
            r"",
        ]

    # Per-quarter from regime breakdown.
    # IMPORTANT: LaTeX command names disallow digits ("2026Q1" inside
    # \newcommand{\...} parses as part of macro-name + trailing text, which
    # silently produces double-definitions). Use Roman labels.
    Q_LABEL = {"2026-Q1": "Qone", "2026-Q2": "Qtwo"}
    for q, qsuf in Q_LABEL.items():
        for p, prefix in POLICY_PREFIX.items():
            sub = regime[(regime.quarter == q) & (regime.policy == p)]
            if sub.empty:
                # Safe default so latex never sees undefined macro.
                lines.append(
                    rf"\newcommand{{\{prefix}APY{qsuf}}}{{---}}"
                )
                continue
            r = sub.iloc[0]
            lines.append(
                rf"\newcommand{{\{prefix}APY{qsuf}}}{{{r.net_apy_pct:.2f}\%}}"
            )
        lines.append(r"")

    # Inherited macros from V1 hourly-paper (V2 §IV LOB recap cites them).
    lines += [
        r"% --- V1 hourly-forecaster macros inherited by V2's §IV LOB recap ---",
        r"\newcommand{\LobGRUwPearson}{0.266}",
        r"\newcommand{\LobLGBMwPearson}{0.168}",
        r"\newcommand{\LobGRUOverLGBM}{58\%}",
        r"\newcommand{\LobFeatureSuffGRU}{0.8\%}",
        r"\newcommand{\LobFeatureSuffLGBM}{71.4\%}",
        r"\newcommand{\ForecastRsq}{-200.55}",
        r"\newcommand{\ForecastDirAcc}{48.80\%}",
        r"\newcommand{\ForecastWPearson}{0.42}",
        r"\newcommand{\ForecastQNineLoss}{0.01}",
        r"% --- V1 H1 bootstrap macros referenced in §I introduction ---",
        r"\newcommand{\SharpeDelta}{+1.667}",
        r"\newcommand{\BootstrapPvalue}{0.121}",
        r"\newcommand{\BootstrapCILow}{-6.459}",
        r"\newcommand{\BootstrapCIHigh}{+11.031}",
        r"\newcommand{\PredictiveSharpe}{143.36}",
        r"\newcommand{\PredictiveAPY}{4.60\%}",
        r"\newcommand{\EMASharpe}{154.02}",
        r"\newcommand{\DataHours}{12{,}895}",
        r"\newcommand{\DataCoverage}{98.5\%}",
        r"\newcommand{\ModelParams}{319\,K}",
        r"\newcommand{\SeqLen}{168}",
        r"\newcommand{\Horizon}{12}",
        r"",
    ]
    # Data window
    lines += [
        r"\newcommand{\NBlocks}{863{,}999}",
        r"\newcommand{\NBlocksFull}{3{,}931{,}200}",
        r"\newcommand{\DataStart}{January 2026}",
        r"\newcommand{\DataEnd}{April 2026}",
        r"\newcommand{\NProtocols}{3}",
        r"\newcommand{\ProtocolList}{Aave V3, Morpho Blue, Euler V2}",
        r"",
        r"% Pass-through for any unfilled \PLACEHOLDER{} cells (compact, no italics).",
        r"\newcommand{\PLACEHOLDER}[1]{#1}",
    ]

    OUT_TEX.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_TEX} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
